
users=1000
train_examples=50
test_examples=100
mnist_path="/crankshaw-local/mnist/data/test.data"
num_events=1000000
worker_threads=2
target_qps=64000
query_batch_size=800
max_features=7
salt_hash=true
feature_batch_size=100

