[package]
name = "clipper"
version = "0.1.0"
authors = ["Dan Crankshaw <dscrankshaw@gmail.com>"]
build = "build.rs"

[[bin]]
name = "clipper"
path = "src/main.rs"

[profile.release]
debug = true

[build-dependencies]
capnpc = "*"

[dependencies]
hyper = "0.7"
capnp = "0.6.1"
gj = "0.1.1"
capnp-rpc = "0.6.1"
rand = "0.3"
time = "0.1"
mio = "0.5"
num_cpus = "0.2"

[dependencies.eventual]
git = "https://github.com/carllerche/eventual"
