
users=200
train_examples=50
test_examples=100
mnist_path="/crankshaw-local/mnist/data/test.data"
num_events=1000000
worker_threads=2
target_qps=1000
query_batch_size=200
max_features=10
salt_hash=true
feature_batch_size=100

