name = "clipper-test"
slo_micros = 20000
# correction_policy = "hello world"
correction_policy = "logistic_regression"
use_lsh = true
input_type = "float"
input_length = 784
window_size = -1
redis_ip = "redis"
redis_port = 6379
# batch_size = -1

num_predict_workers = 8
num_update_workers = 1
# largest prime less than 50000
cache_size = 49999
mnist_path = "/mnist_data/test.data"
# mnist_path = "/crankshaw-local/mnist/data/test.data"
num_benchmark_requests = 500000
target_qps = 500
bench_batch_size = 30

[batching]
strategy = "learned"
sample_size = 1000

# [[models]]
# name = "rf_d1"
# addresses = ["rf_d1_r1:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "rf_d2"
# addresses = ["rf_d2_r1:6001"]
# num_outputs = 1
# version = 1

# [[models]]
# name = "rf_d4"
# addresses = ["rf_d4_r1:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "rf_d8"
# addresses = ["rf_d8_r1:6001"]
# num_outputs = 1
# version = 1

[[models]]
name = "svm"
addresses = ["svm_r1:6001"]
num_outputs = 1
version = 1

# [[models]]
# name = "log_reg"
# addresses = ["log_reg_r1:6001"]
# num_outputs = 1
# version = 1

#################################
# [[models]]
# name = "rf_d16"
# addresses = ["rf_d16_r1:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "rf_d32"
# addresses = ["rf_d32_r1:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "rf_d64"
# addresses = ["rf_d64_r1:6001"]
# num_outputs = 1
# version = 1
#
