name = "clipper-test"
slo_micros = 20000
# correction_policy = "hello world"
correction_policy = "logistic_regression"
use_lsh = true
input_type = "float"
input_length = 784
window_size = -1
redis_ip = "redis"
redis_port = 6379
batch_size = -1

num_predict_workers = 8
num_update_workers = 1
# largest prime less than 50000
cache_size = 49999
mnist_path = "/mnist_data/test.data"
num_benchmark_requests = 1000000
target_qps = 35000
bench_batch_size = 1200


[[models]]
name = "mw1"
addresses = ["mw1_0:6001", "mw1_1:6001", "mw1_2:6001", "mw1_3:6001"]
num_outputs = 1
version = 1

# [[models]]
# name = "mw2"
# addresses = ["mw2:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw3"
# addresses = ["mw3:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw4"
# addresses = ["mw4:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw5"
# addresses = ["mw5:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw6"
# addresses = ["mw6:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw7"
# addresses = ["mw7:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw8"
# addresses = ["mw8:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw9"
# addresses = ["mw9:6001"]
# num_outputs = 1
# version = 1
#
# [[models]]
# name = "mw10"
# addresses = ["mw10:6001"]
# num_outputs = 1
# version = 1
