num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
input_length = 784
num_benchmark_requests = 3000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 1650
target_qps = 110000
name = "DEBUG_sklearn_logreg_1_local_replicas_10_remote_replicas_160906-211312"
salt_cache = true
num_predict_workers = 16
redis_port = 6379
cache_size = 500000
slo_micros = 20000
correction_policy = "logistic_regression"
send_updates = false
[[models]]
version = 1
num_outputs = 1
name = "logistic_reg"
addresses = [ "logistic_reg_r0:6001", "c69.millennium.berkeley.edu:7001", "c69.millennium.berkeley.edu:7002", "c69.millennium.berkeley.edu:7003", "c69.millennium.berkeley.edu:7004", "c69.millennium.berkeley.edu:7005", "c69.millennium.berkeley.edu:7006", "c69.millennium.berkeley.edu:7007", "c69.millennium.berkeley.edu:7008", "c69.millennium.berkeley.edu:7009", "c69.millennium.berkeley.edu:7010",]
[batching]
sample_size = 500
opt_addr = "quantilereg:7777"
strategy = "learned"
