num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
input_length = 784
num_benchmark_requests = 6000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 3000
target_qps = 200000
name = "sklearn_logreg_20_replicas_160906-183353"
salt_cache = true
num_predict_workers = 16
redis_port = 6379
cache_size = 500000
slo_micros = 20000
correction_policy = "logistic_regression"
send_updates = false
[[models]]
version = 1
num_outputs = 1
name = "logistic_reg"
addresses = [ "logistic_reg_r0:6001", "logistic_reg_r1:6001", "logistic_reg_r2:6001", "logistic_reg_r3:6001", "logistic_reg_r4:6001", "logistic_reg_r5:6001", "logistic_reg_r6:6001", "logistic_reg_r7:6001", "logistic_reg_r8:6001", "logistic_reg_r9:6001", "logistic_reg_r10:6001", "logistic_reg_r11:6001", "logistic_reg_r12:6001", "logistic_reg_r13:6001", "logistic_reg_r14:6001", "logistic_reg_r15:6001", "logistic_reg_r16:6001", "logistic_reg_r17:6001", "logistic_reg_r18:6001", "logistic_reg_r19:6001",]
[batching]
sample_size = 500
opt_addr = "quantilereg:7777"
strategy = "learned"
