version: '2'

services:
  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379
  sparkmw:
    image: clipper/spark-mw-dev
    # ports:
    #   - 6001:6001
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/spark_lr_pred_1:/model"
  clipper:
    image: cl-dev
    depends_on:
      - redis
      - sparkmw
    volumes:
      # - /Users/crankshaw/model-serving/data/mnist_data/:/mnist_data
      - "${MNIST_PATH}:/mnist_data"
      - "${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml"
    # ports:
    #   - 1337:1337
