version: '2'

services:
  redis:
    image: clipper/redis
    ports:
      - 6379
  sparkmw:
    image: clipper/spark-mw-dev
    ports:
      - 6001
  clipper:
    image: cl-dev
    links:
      - redis
      - sparkmw
    ports:
      - 1337
    volumes:
      - /Users/crankshaw/clipper/model_wrappers/python/spark_models/spark_lr_pred_1:/model
