salt_update_cache = true
num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
track_blocking_latency = true
input_length = 784
num_benchmark_requests = 2000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 100
target_qps = 15000
name = "ensemble_size_20_trial_5_160914-125816"
cache_hit_rate = 0.0
wait_to_end = false
send_updates = false
report_interval_secs = 30
num_predict_workers = 10
redis_port = 6379
cache_size = 10000000
slo_micros = 20000
correction_policy = "logistic_regression"
salt_cache = true
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_0_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_0_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_1_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_1_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_2_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_2_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_3_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_3_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_4_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_4_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_5_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_5_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_6_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_6_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_7_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_7_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_8_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_8_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_9_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_9_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_10_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_10_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_11_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_11_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_12_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_12_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_13_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_13_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_14_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_14_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_15_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_15_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_16_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_16_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_17_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_17_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_18_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_18_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "sklearn_rf_comp_19_d16"
wait_time_nanos = 4000000
addresses = [ "sklearn_rf_comp_19_d16_r0:6001",]
[batching]
strategy = "aimd"
