salt_update_cache = true
num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
track_blocking_latency = true
input_length = 784
num_benchmark_requests = 32000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 100
target_qps = 1600000
name = "8_local_reps_8_remote_reps_160915-040615"
cache_hit_rate = 0.0
wait_to_end = false
send_updates = false
report_interval_secs = 20
num_predict_workers = 24
redis_port = 6379
cache_size = 10000000
slo_micros = 20000
correction_policy = "logistic_regression"
salt_cache = true
[[models]]
version = 1
num_outputs = 1
name = "spark_svm"
wait_time_nanos = 1000000
addresses = [ "spark_svm_r0:6001", "spark_svm_r1:6001", "spark_svm_r2:6001", "spark_svm_r3:6001", "spark_svm_r4:6001", "spark_svm_r5:6001", "spark_svm_r6:6001", "spark_svm_r7:6001", "c67.millennium.berkeley.edu:7001", "c67.millennium.berkeley.edu:7002", "c67.millennium.berkeley.edu:7003", "c67.millennium.berkeley.edu:7004", "c67.millennium.berkeley.edu:7005", "c67.millennium.berkeley.edu:7006", "c67.millennium.berkeley.edu:7007", "c67.millennium.berkeley.edu:7008",]
[batching]
strategy = "aimd"
