salt_update_cache = true
num_message_encodes = 1
use_lsh = false
window_size = 100
load_generator = "uniform"
input_type = "float"
request_generator = "cached_updates"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 8
input_length = 784
num_benchmark_requests = 2000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 100
target_qps = 500000
name = "DEBUG_window_100_caching_OFF_160913-195823"
cache_hit_rate = 0.0
wait_to_end = false
salt_cache = true
num_predict_workers = 10
redis_port = 6379
cache_size = 10000000
slo_micros = 20000
correction_policy = "logistic_regression"
send_updates = true
[[models]]
version = 1
num_outputs = 1
name = "rf_d16"
addresses = [ "rf_d16_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "spark_svm"
addresses = [ "spark_svm_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "linear_svm"
addresses = [ "linear_svm_r0:6001",]
[[models]]
version = 1
num_outputs = 1
name = "logistic_reg"
addresses = [ "logistic_reg_r0:6001",]
[batching]
strategy = "aimd"
