salt_update_cache = true
num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
track_blocking_latency = true
input_length = 784
num_benchmark_requests = 1000000
redis_ip = "redis"
mnist_path = "/mnist_data/test.data"
bench_batch_size = 100
target_qps = 20000
name = "wait_time_10_sklearn_svm_160914-021304"
cache_hit_rate = 0.0
wait_to_end = false
send_updates = false
report_interval_secs = 30
num_predict_workers = 10
redis_port = 6379
cache_size = 10000000
slo_micros = 20000
correction_policy = "logistic_regression"
salt_cache = true
[[models]]
version = 1
num_outputs = 1
name = "linear_svm"
wait_time_nanos = 10000000
addresses = [ "linear_svm_r0:6001",]
[batching]
strategy = "aimd"
