
name = "clipper-test"
slo_micros = 10000
policy_name = "hello_world"
use_lsh = true

num_predict_workers = 4
num_update_workers = 2


[[models]]
name = "m1"
addresses = ["127.0.0.1:6002", "127.0.0.1:7002", "127.0.0.1:8002"]
num_outputs = 3

[[models]]
name = "m2"
addresses = ["127.0.0.1:6004"]
