
name = "clipper-test"
slo_micros = 10000
correction_policy = "hello world"
use_lsh = true
input_type = "int"
input_length = 784

num_predict_workers = 4
num_update_workers = 0
# largest prime less than 50000
cache_size = 49999


[[models]]
name = "m1"
addresses = ["127.0.0.1:6001"]
num_outputs = 1

# [[models]]
# name = "m2"
# addresses = ["127.0.0.1:6004"]
