
name = "clipper-test"
slo_micros = 20000
# correction_policy = "hello world"
correction_policy = "logistic_regression"
use_lsh = false
input_type = "float"
input_length = 784
window_size = -1
redis_ip = "redis"
redis_port = 6379
# batch_size = -1
results_path = "/tmp/benchmarking_logs"

num_predict_workers = 8
num_update_workers = 1
# largest prime less than 50000
cache_size = 49999
mnist_path = "/mnist_data/test.data"
# mnist_path = "/crankshaw-local/mnist/data/test.data"
num_benchmark_requests = 500000
target_qps = 50000
bench_batch_size = 10000
salt_cache = true

[batching]
strategy = "learned"
sample_size = 500


[[models]]
name = "log_reg"
addresses = ["log_reg_r0:6001","log_reg_r1:6001",]
num_outputs = 1
version = 1

[[models]]
name = "linearsvm"
addresses = ["linearsvm_r0:6001","linearsvm_r1:6001",]
num_outputs = 1
version = 1

[[models]]
name = "rf_d8"
addresses = ["rf_d8_r0:6001","rf_d8_r1:6001",]
num_outputs = 1
version = 1

