[package]

name = "libsvm-sys"
version = "0.1.0"
authors = ["Dan Crankshaw <dscrankshaw@gmail.com>"]
links = "libsvm"
build = "build.rs"


[lib]
name = "libsvm_sys"
path = "src/lib.rs"


[build-dependencies]
gcc = "0.3"

[dev-dependencies]
rand = "0.3"

[dependencies]
libc = "0.2"


