services:
  clipper:
    cpuset: 2-25
    depends_on: [redis, quantilereg, rf_d16_r0, spark_svm_r0, linear_svm_r0, logistic_reg_r0]
    environment: {CLIPPER_BENCH_COMMAND: digits, CLIPPER_CONF_PATH: /tmp/exp_conf.toml}
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/exp_conf.toml:/tmp/exp_conf.toml:ro',
      '${CLIPPER_ROOT}/experiments_logs/feedback_caching:/tmp/benchmarking_logs']
  linear_svm_r0:
    cpuset: 28-28
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  logistic_reg_r0:
    cpuset: 29-29
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  quantilereg: {cpuset: 1-1, image: clipper/quantile-reg}
  redis: {cpuset: 0-0, image: 'redis:alpine'}
  rf_d16_r0:
    cpuset: 26-26
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  spark_svm_r0:
    cpuset: 27-27
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
version: '2'
