services:
  clipper:
    cpuset: 2-11
    depends_on: [redis, quantilereg, spark_svm_r0]
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml:ro',
      '${CLIPPER_ROOT}/benchmarking_logs/caching:/tmp/benchmarking_logs']
  quantilereg: {cpuset: 1-1, image: clipper/quantile-reg}
  redis: {cpuset: 0-0, image: 'redis:alpine'}
  spark_svm_r0:
    cpuset: 12-12
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
version: '2'
