services:
  clipper:
    cpuset: 2-19
    depends_on: [redis, quantilereg, kernel_svm_r0]
    environment: {CLIPPER_BENCH_COMMAND: digits, CLIPPER_CONF_PATH: /tmp/exp_conf.toml}
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/exp_conf.toml:/tmp/exp_conf.toml:ro',
      '${CLIPPER_ROOT}/experiments_logs/caching-pred-thruput:/tmp/benchmarking_logs']
  kernel_svm_r0:
    cpuset: 20-20
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/svm_pred3/:/model:ro']
  quantilereg: {cpuset: 1-1, image: clipper/quantile-reg}
  redis: {cpuset: 0-0, image: 'redis:alpine'}
version: '2'
