services:
  clipper:
    cpuset: 2-11
    depends_on: [redis, quantilereg, spark_svm_r0, spark_svm_r1, spark_svm_r2, spark_svm_r3,
      spark_svm_r4, spark_svm_r5, logistic_reg_r0, logistic_reg_r1, logistic_reg_r2,
      logistic_reg_r3, logistic_reg_r4, logistic_reg_r5, rf_d16_r0, rf_d16_r1, rf_d16_r2,
      rf_d16_r3, rf_d16_r4, rf_d16_r5, linear_svm_r0, linear_svm_r1, linear_svm_r2,
      linear_svm_r3, linear_svm_r4, linear_svm_r5, rf_d8_r0, rf_d8_r1, rf_d8_r2, rf_d8_r3,
      rf_d8_r4, rf_d8_r5]
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml:ro',
      '${CLIPPER_ROOT}/benchmarking_logs/container-isolation:/tmp/benchmarking_logs']
  linear_svm_r0:
    cpuset: 30-30
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  linear_svm_r1:
    cpuset: 31-31
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  linear_svm_r2:
    cpuset: 32-32
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  linear_svm_r3:
    cpuset: 33-33
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  linear_svm_r4:
    cpuset: 34-34
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  linear_svm_r5:
    cpuset: 35-35
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  logistic_reg_r0:
    cpuset: 18-18
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  logistic_reg_r1:
    cpuset: 19-19
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  logistic_reg_r2:
    cpuset: 20-20
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  logistic_reg_r3:
    cpuset: 21-21
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  logistic_reg_r4:
    cpuset: 22-22
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  logistic_reg_r5:
    cpuset: 23-23
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro']
  quantilereg: {cpuset: 1-1, image: clipper/quantile-reg}
  redis: {cpuset: 0-0, image: 'redis:alpine'}
  rf_d16_r0:
    cpuset: 24-24
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d16_r1:
    cpuset: 25-25
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d16_r2:
    cpuset: 26-26
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d16_r3:
    cpuset: 27-27
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d16_r4:
    cpuset: 28-28
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d16_r5:
    cpuset: 29-29
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  rf_d8_r0:
    cpuset: 36-36
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  rf_d8_r1:
    cpuset: 37-37
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  rf_d8_r2:
    cpuset: 38-38
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  rf_d8_r3:
    cpuset: 39-39
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  rf_d8_r4:
    cpuset: 40-40
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  rf_d8_r5:
    cpuset: 41-41
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro']
  spark_svm_r0:
    cpuset: 12-12
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r1:
    cpuset: 13-13
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r2:
    cpuset: 14-14
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r3:
    cpuset: 15-15
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r4:
    cpuset: 16-16
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r5:
    cpuset: 17-17
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
version: '2'
