services:
  clipper:
    cpuset: 1-28
    depends_on: [redis, spark_svm_r0, spark_svm_r1, spark_svm_r2, spark_svm_r3, spark_svm_r4,
      spark_svm_r5, spark_svm_r6]
    environment: {CLIPPER_BENCH_COMMAND: digits, CLIPPER_CONF_PATH: /tmp/exp_conf.toml}
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/exp_conf.toml:/tmp/exp_conf.toml:ro',
      '${CLIPPER_ROOT}/experiments_logs/replica_scaling_fast_network:/tmp/benchmarking_logs']
  redis: {cpuset: 0-0, image: 'redis:alpine'}
  spark_svm_r0:
    cpuset: 29-29
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r1:
    cpuset: 30-30
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r2:
    cpuset: 31-31
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r3:
    cpuset: 32-32
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r4:
    cpuset: 33-33
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r5:
    cpuset: 34-34
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
  spark_svm_r6:
    cpuset: 35-35
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
version: '2'
