services:
  clipper:
    cpuset: 2-19
    depends_on: [redis, quantilereg, noop_r0, rf_d16_r0, spark_svm_r0]
    environment: {CLIPPER_BENCH_COMMAND: digits, CLIPPER_CONF_PATH: /tmp/exp_conf.toml}
    image: cl-dev-digits
    volumes: ['${MNIST_PATH}:/mnist_data:ro', '${CLIPPER_ROOT}/exp_conf.toml:/tmp/exp_conf.toml:ro',
      '${CLIPPER_ROOT}/experiments_logs/mw-contention:/tmp/benchmarking_logs']
  noop_r0:
    cpuset: 20-20
    image: clipper/noop-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro']
  quantilereg: {cpuset: 1-1, image: clipper/quantile-reg}
  redis: {cpuset: 0-0, image: 'redis:alpine'}
  rf_d16_r0:
    cpuset: 21-21
    image: clipper/sklearn-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro']
  spark_svm_r0:
    cpuset: 22-22
    image: clipper/spark-mw-dev
    volumes: ['${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro']
version: '2'
