
version: '2'

services:
  redis:
    image: redis:alpine
  clipper:
    image: cl-dev
    depends_on:
      - redis
      - log_reg_r0
      - log_reg_r1
      - linearsvm_r0
      - linearsvm_r1
      - rf_d8_r0
      - rf_d8_r1
      - rf_d16_r0
      - rf_d16_r1
      - svm_pred3_r0
      - svm_pred3_r1

    volumes:
      - "${MNIST_PATH}:/mnist_data:ro"
      - "${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml:ro"
      - "${CLIPPER_ROOT}/benchmarking_logs:/tmp/benchmarking_logs"


  log_reg_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


  log_reg_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


  linearsvm_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/linearsvm_pred3.pkl


  linearsvm_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/linearsvm_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/linearsvm_pred3.pkl


  rf_d8_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/50rf_pred3_depth8.pkl


  rf_d8_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth8/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/50rf_pred3_depth8.pkl


  rf_d16_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/50rf_pred3_depth16.pkl


  rf_d16_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/50rf_pred3_depth16/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/50rf_pred3_depth16.pkl


  svm_pred3_r0:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model


  svm_pred3_r1:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model


