
version: '2'

services:
  redis:
    image: redis:alpine
  clipper:
    image: cl-dev
    depends_on:
      - redis
      - log_reg_xx_r0
      - log_reg_xx_r1
      - log_reg_yy_r0
      - log_reg_yy_r1

    volumes:
      - "${MNIST_PATH}:/mnist_data:ro"
      - "${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml:ro"
      - "${CLIPPER_ROOT}/benchmarking_logs/thruput_mw_debug:/tmp/benchmarking_logs"


  log_reg_xx_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


  log_reg_xx_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


  log_reg_yy_r0:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


  log_reg_yy_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/log_regression_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/log_regression_pred3.pkl


