version: '2'

services:
  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379
  clipper:
    image: cl-dev
    depends_on:
      - redis
      - mw1_0
      # - mw1_1
      # - mw1_2
      # - mw1_3
      - mw2
      - mw3
      # - mw4
      # - mw5
      # - mw6
      # - mw7
      # - mw8
      # - mw9
      # - mw10
      - svm_r1
    volumes:
      # - /Users/crankshaw/model-serving/data/mnist_data/:/mnist_data
      - "${MNIST_PATH}:/mnist_data:ro"
      - "${CLIPPER_ROOT}/digits_bench.toml:/tmp/digits_bench.toml:ro"
    # ports:
    #   - 1337:1337
  mw1_0:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_1:/model:ro"
  mw1_1:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_1:/model:ro"
  mw1_2:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_1:/model:ro"
  mw1_3:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_1:/model:ro"




  mw2:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_2:/model:ro"
  mw3:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_3:/model:ro"
  mw4:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_4:/model:ro"
  mw5:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_5:/model:ro"
  mw6:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_6:/model:ro"
  mw7:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_7:/model:ro"
  mw8:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_8:/model:ro"
  mw9:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_9:/model:ro"
  mw10:
    image: clipper/spark-mw-dev
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/spark_models/svm_predict_10:/model:ro"

  svm_r1:
    image: clipper/sklearn-mw
    volumes:
      - "${CLIPPER_ROOT}/model_wrappers/python/sklearn_models/svm_pred3/:/model:ro"
    environment:
      - CLIPPER_MODEL_PATH=/model/svm_pred3.pkl
