
name = "cifar10-test"
correction_policy = "logistic_regression"
redis_port = 6379
salt_update_cache = false
num_message_encodes = 1
use_lsh = false
window_size = 10
# load_generator = "uniform"
input_type = "float"
# request_generator = "cached_updates"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
input_length = 3072  # 299 * 299 * 3
num_benchmark_requests = 5000000
redis_ip = "localhost"
cifar_path = "/crankshaw-local/cifar10.txt"
bench_batch_size = 100000
target_qps = 500000
wait_to_end = true
salt_cache = true
num_predict_workers = 8
cache_size = 1000000
slo_micros = 50000


[batching]
strategy = "static"
batch_size = 128

[[models]]
name = "tf-cifar10"
addresses = ["127.0.0.1:6001"]
num_outputs = 1
version = 1

