num_message_encodes = 1
use_lsh = false
window_size = 100
load_generator = "uniform"
input_type = "float"
request_generator = "balanced"
results_path = "/crankshaw-local/clipper/benchmarks"
num_update_workers = 1
input_length = 784
num_benchmark_requests = 1000000
redis_ip = "localhost"
mnist_path = "/crankshaw-local/mnist/data/test.data"
bench_batch_size = 500
target_qps = 80000
name = "digits-bench-python-noop"
wait_to_end = true
salt_cache = true
num_predict_workers = 8
redis_port = 6379
cache_size = 1000000
slo_micros = 20000
correction_policy = "logistic_regression"
send_updates = false

[batching]
strategy = "static"
batch_size = 250

[[models]]
version = 1
num_outputs = 1
name = "noop-python"
addresses = [ "127.0.0.1:7777"]

