salt_update_cache = true
num_message_encodes = 1
use_lsh = false
window_size = -1
load_generator = "uniform"
input_type = "float"
request_generator = "cached_updates"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
input_length = 784
num_benchmark_requests = 25000000
redis_ip = "localhost"
mnist_path = "/mnist_data/test.data"
target_qps = 1000000
name = "latency_breakdown_160909-182718"
wait_to_end = false
salt_cache = true
num_predict_workers = 8
redis_port = 6379
cache_size = 1000000
slo_micros = 20000
correction_policy = "logistic_regression"
send_updates = true
[[models]]
version = 1
num_outputs = 1
name = "noop"
addresses = [ "127.0.0.1:6001",]
[batching]
batch_size = 250
strategy = "static"
