
name = "inception-test"
correction_policy = "logistic_regression"
redis_port = 6379
salt_update_cache = false
num_message_encodes = 1
use_lsh = false
window_size = 10
# load_generator = "uniform"
input_type = "float"
# request_generator = "cached_updates"
results_path = "/tmp/benchmarking_logs"
num_update_workers = 1
input_length = 268203  # 299 * 299 * 3
num_benchmark_requests = 2000
redis_ip = "localhost"
mnist_path = "/crankshaw-local/mnist/data/test.data"
imagenet_path = "/crankshaw-local/clipper/examples/inception_input_data.csv"
bench_batch_size = 5
target_qps = 100
wait_to_end = true
salt_cache = true
num_predict_workers = 8
cache_size = 1000000
slo_micros = 200000


[batching]
strategy = "aimd"

[[models]]
name = "inception"
addresses = ["127.0.0.1:6001"]
num_outputs = 1
version = 1

