[package]

name = "liblinear-sys"
version = "0.1.0"
authors = ["Dan Crankshaw <dscrankshaw@gmail.com>"]
links = "liblinear"
build = "build.rs"


[lib]
name = "liblinear_sys"
path = "src/lib.rs"


[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2"


